In [ ]:
 from nltk.corpus import wordnet
 from nltk.corpus import wordnet as wn
 

In [ ]:
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import re

In [ ]:
!pip install nltk
!pip install gensim


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import nltk
from nltk.wsd import lesk ##
from nltk.corpus import wordnet, wordnet_ic##
nltk.download('wordnet')
nltk.download('wordnet_ic') 
nltk.download('omw-1.4')
nltk.download('all')##
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer##

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet_ic.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nl

In [ ]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english')) 

In [ ]:
from nltk.tokenize import word_tokenize

#Resnik Similarity

In [ ]:
# Defining Infinity
infinity = float('inf')

In [ ]:
# Importing the Brown Corpus
brown_ic = wordnet_ic.ic('ic-brown.dat')

In [ ]:
def closest_synsets(word_1: str, word_2: str):
    word_1 = wordnet.synsets(word_1)
    word_2 = wordnet.synsets(word_2)
    max_similarity = -infinity
    try:
        synset_1_shortest = word_1[0]
        synset_2_shortest = word_2[0]
    except:
        return None, None, -infinity

    for synset_1 in word_1:
        for synset_2 in word_2:
            if synset_1.pos() != synset_2.pos():
                continue
            similarity = synset_1.res_similarity(synset_2, ic=brown_ic)
            if similarity > max_similarity:
                max_similarity = similarity
                synset_1_shortest = synset_1
                synset_2_shortest = synset_2

    return synset_1_shortest, synset_2_shortest, max_similarity

In [ ]:
word_1 = 'java'
word_2 = 'language'
word_1_synset, word_2_synset, similarity = closest_synsets(word_1, word_2)

print(word_1.capitalize() + ' Definition:', word_1_synset.definition())
print(word_2.capitalize() + ' Definition:', word_2_synset.definition())
print('similarity:', similarity)

Java Definition: a platform-independent object-oriented programming language
Language Definition: a systematic means of communicating by the use of sounds or conventional symbols
similarity: 5.792086967391197


In [ ]:
word_1 = 'java'
word_2 = 'island'
word_1_synset, word_2_synset, similarity = closest_synsets(word_1, word_2)

print(word_1.capitalize() + ' Definition:', word_1_synset.definition())
print(word_2.capitalize() + ' Definition:', word_2_synset.definition())
print('similarity:', similarity)

Java Definition: an island in Indonesia to the south of Borneo; one of the world's most densely populated regions
Island Definition: a land mass (smaller than a continent) that is surrounded by water
similarity: 6.688645509739946


In [ ]:
word_1 = 'nickel'
word_2 = 'dime'
word_1_synset, word_2_synset, similarity = closest_synsets(word_1, word_2)

print(word_1.capitalize() + ' Definition:', word_1_synset.definition())
print(word_2.capitalize() + ' Definition:', word_2_synset.definition())
print('similarity:', similarity)

Nickel Definition: a United States coin worth one twentieth of a dollar
Dime Definition: a United States coin worth one tenth of a dollar
similarity: 7.455288045755159


In [ ]:
word_1 = 'nickel'
word_2 = 'gold'
word_1_synset, word_2_synset, similarity = closest_synsets(word_1, word_2)

print(word_1.capitalize() + ' Definition:', word_1_synset.definition())
print(word_2.capitalize() + ' Definition:', word_2_synset.definition())
print('similarity:', similarity)

Nickel Definition: a hard malleable ductile silvery metallic element that is resistant to corrosion; used in alloys; occurs in pentlandite and smaltite and garnierite and millerite
Gold Definition: a soft yellow malleable ductile (trivalent and univalent) metallic element; occurs mainly as nuggets in rocks and alluvial deposits; does not react with most chemicals but is attacked by chlorine and aqua regia
similarity: 5.442191710437843


#Cosine similarity

In [ ]:
# Program to measure the similarity between 
# two sentences using cosine similarity.
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
  
# X = input("Enter first string: ").lower()
# Y = input("Enter second string: ").lower()
X ="I love horror movies"
Y ="Lights out is a horror movie"
  
# tokenization
X_list = word_tokenize(X) 
Y_list = word_tokenize(Y)
  
# sw contains the list of stopwords
sw = stopwords.words('english') 
l1 =[];l2 =[]

# remove stop words from the string
X_set = {w for w in X_list if not w in sw} 
Y_set = {w for w in Y_list if not w in sw}
  
# form a set containing keywords of both strings 
rvector = X_set.union(Y_set) 
for w in rvector:
    if w in X_set: l1.append(1) # create a vector
    else: l1.append(0)
    if w in Y_set: l2.append(1)
    else: l2.append(0)
c = 0
  
# cosine formula 
for i in range(len(rvector)):
        c+= l1[i]*l2[i]
cosine = c / float((sum(l1)*sum(l2))**0.5)
print("similarity: ", cosine)

similarity:  0.2886751345948129


#Lesk Algorithm

In [ ]:
def get_semantic(seq, key_word):
	
	# Tokenization of the sequence
	temp = word_tokenize(seq)
	
	# Retrieving the definition
	# of the tokens
	temp = lesk(temp, key_word)
	return temp.definition()


In [ ]:
keyword = 'book'
seq1 = 'I love reading books on coding.'
seq2 = 'The table was already booked by someone else.'

print(get_semantic(seq1, keyword))
print(get_semantic(seq2, keyword))


a number of sheets (ticket or stamps etc.) bound together on one edge
arrange for and reserve (something for someone else) in advance


In [ ]:
keyword = 'jam'
seq1 = 'My mother prepares very yummy jam.'
seq2 = 'Signal jammers are the reason for no signal.'

print(get_semantic(seq1, keyword))
print(get_semantic(seq2, keyword))


press tightly together or cram
deliberate radiation or reflection of electromagnetic energy for the purpose of disrupting enemy use of electronic devices or systems


#Count Vectorizer


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    'He is playing in the field.',
    'He is running towards the football.',
    'The football game ended.',
    'It started raining while everyone was playing in the field.'
]

vectorizer = CountVectorizer()
sentence_vectors = vectorizer.fit_transform(sentences)

print(sentence_vectors.toarray())


[[0 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0]
 [1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 1 1]]


#TF-IDF

In [ ]:
# assign documents
d0 = 'Geeks for geeks'
d1 = 'Geeks'
d2 = 'r2j'
 
# merge documents into a single corpus
string = [d0, d1, d2]

In [ ]:
# create object
tfidf = TfidfVectorizer()
 
# get tf-df values
result = tfidf.fit_transform(string)

In [ ]:
# get idf values
print('\nidf values:')
for ele1, ele2 in zip(tfidf.get_feature_names(), tfidf.idf_):
	print(ele1, ':', ele2)



idf values:
for : 1.6931471805599454
geeks : 1.2876820724517808
r2j : 1.6931471805599454


In [ ]:
# get indexing
print('\nWord indexes:')
print(tfidf.vocabulary_)

# display tf-idf values
print('\ntf-idf value:')
print(result)

# in matrix form
print('\ntf-idf values in matrix form:')
print(result.toarray())



Word indexes:
{'geeks': 1, 'for': 0, 'r2j': 2}

tf-idf value:
  (0, 0)	0.5493512310263033
  (0, 1)	0.8355915419449176
  (1, 1)	1.0
  (2, 2)	1.0

tf-idf values in matrix form:
[[0.54935123 0.83559154 0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]]


#Hashing Vectorizer
 convert any word into it’s hash and does not require the generation of any vocabulary.



In [ ]:
from sklearn.feature_extraction.text import HashingVectorizer

sentences = [
    'He is playing in the field.',
    'He is running towards the football.',
    'The football game ended.',
    'It started raining while everyone was playing in the field.'
]

vectorizer = HashingVectorizer(norm = None, n_features = 17)
sentence_vectors = vectorizer.fit_transform(sentences)
print(sentence_vectors.toarray())

[[ 0.  1.  0.  0.  1.  0.  0.  0.  1.  0.  0. -1. -1.  0.  0.  1.  0.]
 [ 1.  1.  0.  0.  1.  0.  0.  0.  1.  0.  0. -2.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0. -1.  0.  0.  0. -1.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.  0. -1.  0.  0.  0. -1. -1. -2.  0. -1.  1.  0.]]


#Word2Vec

In [ ]:
from gensim.models import word2vec

sentences = [
    'He is playing in the field.',
    'He is running towards the football.',
    'The football game ended.',
    'It started raining while everyone was playing in the field.'
]

for i, sentence in enumerate(sentences):
	tokenized= []
	for word in sentence.split(' '):
		word = word.split('.')[0]
		word = word.lower()
		tokenized.append(word)
	sentences[i] = tokenized

model = word2vec.Word2Vec(sentences, workers = 1, size = 2, min_count = 1, window = 3, sg = 0)
similar_word = model.wv.most_similar('football')[0]
print("Most common word to football is: {}".format(similar_word[0]))


Most common word to football is: it


In [ ]:
# Python program to generate word vectors using Word2Vec

# importing all necessary modules
from nltk.tokenize import sent_tokenize, word_tokenize
import warnings

warnings.filterwarnings(action = 'ignore')

import gensim
from gensim.models import Word2Vec

# Reads ‘alice.txt’ file
sample = open("alice.txt")
s = sample.read()

# Replaces escape character with space
f = s.replace("\n", " ")

data = []

# iterate through each sentence in the file
for i in sent_tokenize(f):
	temp = []
	
	# tokenize the sentence into words
	for j in word_tokenize(i):
		temp.append(j.lower())

	data.append(temp)

# Create CBOW model
model1 = gensim.models.Word2Vec(data, min_count = 1, size = 100, window = 5)

# Print results
print("Cosine similarity between 'alice' " +
			"and 'wonderland' - CBOW : ",
	model1.wv.similarity('alice', 'wonderland'))
	
print("Cosine similarity between 'alice' " +
				"and 'machines' - CBOW : ",
	model1.wv.similarity('alice', 'machines'))

# Create Skip Gram model
model2 = gensim.models.Word2Vec(data, min_count = 1, size = 100,
											window = 5, sg = 1)

# Print results
print("Cosine similarity between 'alice' " +
		"and 'wonderland' - Skip Gram : ",
	model2.wv.similarity('alice', 'wonderland'))
	
print("Cosine similarity between 'alice' " +
			"and 'machines' - Skip Gram : ",
	model2.wv.similarity('alice', 'machines'))


Cosine similarity between 'alice' and 'wonderland' - CBOW :  0.9870889
Cosine similarity between 'alice' and 'machines' - CBOW :  0.91299176


Cosine similarity between 'alice' and 'wonderland' - Skip Gram :  0.69089866
Cosine similarity between 'alice' and 'machines' - Skip Gram :  0.86342365


#GloVe

In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip

--2023-02-18 11:41:58--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2023-02-18 11:41:59--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2023-02-18 11:41:59--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glov

In [ ]:
!unzip glove*.zip

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [ ]:
# code for Glove word embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

x = {'text', 'the', 'leader', 'prime',	'natural', 'language'}

# create the dict.
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)

# number of unique words in dict.
print("Number of unique words in dictionary=",
	len(tokenizer.word_index))
print("Dictionary is = ", tokenizer.word_index)

# vocab: 'the': 1, mapping of words with
# integers in seq. 1,2,3..
# embedding: 1->dense vector
def embedding_for_vocab(filepath, word_index,
						embedding_dim):
	vocab_size = len(word_index) + 1
	
	# Adding again 1 because of reserved 0 index
	embedding_matrix_vocab = np.zeros((vocab_size,
									embedding_dim))

	with open(filepath, encoding="utf8") as f:
		for line in f:
			word, *vector = line.split()
			if word in word_index:
				idx = word_index[word]
				embedding_matrix_vocab[idx] = np.array(
					vector, dtype=np.float32)[:embedding_dim]

	return embedding_matrix_vocab


# matrix for vocab: word_index
embedding_dim = 50
embedding_matrix_vocab = embedding_for_vocab(	'glove.6B.50d.txt', tokenizer.word_index,
embedding_dim)

print("Dense vector for first word is => ",	embedding_matrix_vocab[1])


Number of unique words in dictionary= 6
Dictionary is =  {'natural': 1, 'text': 2, 'language': 3, 'leader': 4, 'prime': 5, 'the': 6}
Dense vector for first word is =>  [ 0.44264999  0.84764999 -0.4598      0.67992997  0.13841     0.39456001
 -0.17343    -0.64055002  0.86439002  0.81624001  0.75738001  0.41143
  1.09350002 -0.30068001 -0.08486     0.51784003  1.08700001  0.45061001
 -0.49595001 -0.60650003 -0.16749001 -0.28557    -0.043719   -0.86154002
  0.3396     -0.75239998 -0.33206001  0.24668001  1.00209999  0.71923
  3.30769992 -0.64754999  0.16509999 -0.91650999 -0.035363    0.21794
 -0.87897003  0.37801     0.66733003  0.42054    -0.21387     0.15917
  0.52244997  0.20587    -0.16714001  0.58058    -0.36827999  0.035571
  0.014099   -0.24817   ]


#fastText
fastText is another word embedding method that is an extension of the word2vec model. Instead of learning vectors for words directly, fastText represents each word as an n-gram of characters
fastText works well with rare words. So even if a word wasn’t seen during training, it can be broken down into n-grams to get its embeddings.

Word2vec and GloVe both fail to provide any vector representation for words that are not in the model dictionary. This is a huge advantage of this method.  

In [ ]:
!wget https://github.com/facebookresearch/fastText/archive/v0.9.2.zip
!unzip v0.9.2.zip
!cd fastText-0.9.2
!make

--2023-02-19 17:10:07--  https://github.com/facebookresearch/fastText/archive/v0.9.2.zip
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/facebookresearch/fastText/zip/refs/tags/v0.9.2 [following]
--2023-02-19 17:10:07--  https://codeload.github.com/facebookresearch/fastText/zip/refs/tags/v0.9.2
Resolving codeload.github.com (codeload.github.com)... 140.82.114.10
Connecting to codeload.github.com (codeload.github.com)|140.82.114.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘v0.9.2.zip’

v0.9.2.zip              [  <=>               ]   4.17M  15.7MB/s    in 0.3s    

2023-02-19 17:10:08 (15.7 MB/s) - ‘v0.9.2.zip’ saved [4369852]

Archive:  v0.9.2.zip
5b5943c118b0ec5fb9cd8d20587de2b2d3966dfe
   creating: fastText-0.9.2/
   creating: fastText-0.9.2/.circleci/
 

In [ ]:
!fasttext skipgram -input amazon_reviews.txt -output model_trained

/bin/bash: fasttext: command not found
